[universal]
dark_theme = "Dark"
light_theme = "Light"

[ru]
publications = "Публикации"
podcasts = "Подкасты"
talks = "Выступления"
read_more = "Читать больше"
show_more = "Показать еще"
switch_language = "Switch on"
other_language = "@English"
other_language_code = "en"

[en]
publications = "Publications"
podcasts = "Podcasts"
talks = "Talks"
read_more = "Read more"
show_more = "Show more"
switch_language = "Перейти на"
other_language = "@русский"
other_language_code = "ru"